# Generated by Django 3.2.7 on 2021-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='count_visitor',
            field=models.IntegerField(default=0),
        ),
    ]
