# Generated by Django 3.2.7 on 2021-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211205_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count_visitor',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
