# Generated by Django 3.2.7 on 2021-12-14 14:30

import collagepaper.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('collage_id', models.AutoField(primary_key=True, serialize=False)),
                ('collage_name', models.CharField(max_length=255)),
                ('collage_code', models.CharField(max_length=25)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_subject', models.CharField(max_length=100)),
                ('paper_code', models.AutoField(primary_key=True, serialize=False)),
                ('paper_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1900), collagepaper.models.max_value_current_year])),
                ('paper_semester', models.IntegerField()),
                ('pdf_paper', models.FileField(upload_to='collagepaper/')),
                ('branch', models.ManyToManyField(to='collagepaper.Branch')),
                ('collage', models.ManyToManyField(to='collagepaper.Collage')),
            ],
        ),
    ]
